# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for detail

version: 2

# Set python version and other tools
build:
  os: ubuntu-24.04-lts
  tools:
    python: "3.13.3"
  jobs:
    pre_build:
      # Generate on-the-fly Sphynx config from Jupyter Books'2 _config.yml
      - "jupyter-book config sphinx docs/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - jupyter-book
        
formats:
  - pdf
  - epub